import Head from 'next/head'
import styles from '../styles/Home.module.css'
// import { Footer, Main } from './components'
import Footer from './components/Footer'
import Main from './components/Main'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>this page is about page</div>
            <Main />
            <Footer />
        </div>
    )
}
